name: PyPI

on:
  release:
    types:
      - created

jobs:
  job:
    name: PyPI
    runs-on: ubuntu-latest
    env:
      POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip install poetry==1.7.1 && poetry publish --build
